### ISSUE TITLE
Operation error

### ISSUE THREAD

**Issue by rongzhou861122** [pkhungurn/talking-head-anime-2-demo#12]
Traceback (most recent call last):
  File "tha2/app/manual_poser.py", line 323, in update_result_image_panel
    output_image = self.poser.pose(self.torch_source_image, pose, output_index)[0].detach().cpu()
  File "C:\Users\mayn\Desktop\talking-head-anime-2-demo-main\talking-head-anime-2-demo-main\tha2\poser\general_poser_02.py", line 54, in pose
    output_list = self.get_posing_outputs(image, pose)
  File "C:\Users\mayn\Desktop\talking-head-anime-2-demo-main\talking-head-anime-2-demo-main\tha2\poser\general_poser_02.py", line 58, in get_posing_outputs
    modules = self.get_modules()
  File "C:\Users\mayn\Desktop\talking-head-anime-2-demo-main\talking-head-anime-2-demo-main\tha2\poser\general_poser_02.py", line 39, in get_modules
    module = self.module_loaders[key]()
  File "C:\Users\mayn\Desktop\talking-head-anime-2-demo-main\talking-head-anime-2-demo-main\tha2\poser\modes\mode_20.py", line 269, in <lambda>
    lambda: load_eyebrow_decomposer(module_file_names[KEY_EYEBROW_DECOMPOSER]),
  File "C:\Users\mayn\Desktop\talking-head-anime-2-demo-main\talking-head-anime-2-demo-main\tha2\poser\modes\mode_20.py", line 146, in load_eyebrow_decomposer
    module.load_state_dict(torch_load(file_name))
  File "C:\Users\mayn\Desktop\talking-head-anime-2-demo-main\talking-head-anime-2-demo-main\tha2\util.py", line 23, in torch_load
    with open(file_name, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/eyebrow_decomposer.pt'

**Comment by dragonmeteor** [comment]
Sorry for not answering for a very long time.

The problem indicates that you did not put the mode files (the "data/eyebrow_decomposer.pt") at the right place. Have you downloaded the model files and unzipped them into the right directory?
