### ISSUE TITLE
KeyError: 'eyebrow_decomposer'

### ISSUE THREAD

**Issue by emoto-yasushi** [pkhungurn/talking-head-anime-2-demo#33]
Hi,

I have successfully used Anaconda to launch your app. I was able to Load the images with no problem.
Then I tried to connect with the iFacialMocap desktop app.

Then I got a bunch of messages like the following.
When does this message happen?

And the Loaded image is not moving, only the green parameter below is moving.
The green bar is moving, so the connection itself should be working, but I am wondering why the image is not moving.

I am using a gaming laptop with Windows 11 and RTX2080 Super.

```
Traceback (most recent call last):
  File "tha2/app/ifacialmocap_puppeteer.py", line 406, in update_result_image_bitmap
    output_image = self.poser.pose(self.torch_source_image, pose, output_index)[0].detach().cpu()
  File "C:\Users\emoto\Documents\talking-head-anime-2-demo-main\tha2\poser\general_poser_02.py", line 54, in pose
    output_list = self.get_posing_outputs(image, pose)
  File "C:\Users\emoto\Documents\talking-head-anime-2-demo-main\tha2\poser\general_poser_02.py", line 69, in get_posing_outputs
    return self.output_list_func(modules, batch, outputs)
  File "C:\Users\emoto\Documents\talking-head-anime-2-demo-main\tha2\poser\modes\mode_20.py", line 57, in func
    output = self.get_output(KEY_ALL_OUTPUT, modules, batch, outputs)
  File "C:\Users\emoto\Documents\talking-head-anime-2-demo-main\tha2\compute\cached_computation_protocol.py", line 19, in get_output
    output = self.compute_output(key, modules, batch, outputs)
  File "C:\Users\emoto\Documents\talking-head-anime-2-demo-main\tha2\poser\modes\mode_20.py", line 114, in compute_output
    combiner_output = self.get_output(KEY_COMBINER_OUTPUT, modules, batch, outputs)
  File "C:\Users\emoto\Documents\talking-head-anime-2-demo-main\tha2\compute\cached_computation_protocol.py", line 19, in get_output
    output = self.compute_output(key, modules, batch, outputs)
  File "C:\Users\emoto\Documents\talking-head-anime-2-demo-main\tha2\poser\modes\mode_20.py", line 102, in compute_output
    face_rotater_output = self.get_output(KEY_FACE_ROTATER_OUTPUT, modules, batch, outputs)
  File "C:\Users\emoto\Documents\talking-head-anime-2-demo-main\tha2\compute\cached_computation_protocol.py", line 19, in get_output
    output = self.compute_output(key, modules, batch, outputs)
  File "C:\Users\emoto\Documents\talking-head-anime-2-demo-main\tha2\poser\modes\mode_20.py", line 92, in compute_output
    face_morpher_output = self.get_output(KEY_FACE_MORPHER_OUTPUT, modules, batch, outputs)
  File "C:\Users\emoto\Documents\talking-head-anime-2-demo-main\tha2\compute\cached_computation_protocol.py", line 19, in get_output
    output = self.compute_output(key, modules, batch, outputs)
  File "C:\Users\emoto\Documents\talking-head-anime-2-demo-main\tha2\poser\modes\mode_20.py", line 81, in compute_output
    eyebrow_morphing_combiner_output = self.get_output(
  File "C:\Users\emoto\Documents\talking-head-anime-2-demo-main\tha2\compute\cached_computation_protocol.py", line 19, in get_output
    output = self.compute_output(key, modules, batch, outputs)
  File "C:\Users\emoto\Documents\talking-head-anime-2-demo-main\tha2\poser\modes\mode_20.py", line 71, in compute_output
    eyebrow_decomposer_output = self.get_output(KEY_EYEBROW_DECOMPOSER_OUTPUT, modules, batch, outputs)
  File "C:\Users\emoto\Documents\talking-head-anime-2-demo-main\tha2\compute\cached_computation_protocol.py", line 19, in get_output
    output = self.compute_output(key, modules, batch, outputs)
  File "C:\Users\emoto\Documents\talking-head-anime-2-demo-main\tha2\poser\modes\mode_20.py", line 69, in compute_output
    return modules[KEY_EYEBROW_DECOMPOSER].forward_from_batch([input_image])
KeyError: 'eyebrow_decomposer'
```

**Comment by dragonmeteor** [comment]
Have you loaded and unzip the models in the right directory?

**Comment by emoto-yasushi** [comment]
Thanks for the reply.
I had overlooked that step.
Problem solved and it worked correctly in my environment.
Great software!
